import { getArtifact } from "@/lib/supabase-rest";
import { makeZip } from "@/lib/zip";

export const runtime = "nodejs";

function slugify(s: string): string {
  return (s || "site").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "site";
}

/** The files of a minimal, runnable Next.js + Tailwind project wrapping the
 *  generated page component. */
function nextProject(slug: string, pageSource: string): { name: string; content: string }[] {
  return [
    {
      name: "package.json",
      content: JSON.stringify(
        {
          name: slug,
          version: "0.1.0",
          private: true,
          scripts: { dev: "next dev", build: "next build", start: "next start" },
          dependencies: { next: "^14.2.0", react: "^18.3.0", "react-dom": "^18.3.0" },
          devDependencies: {
            typescript: "^5",
            "@types/node": "^20",
            "@types/react": "^18",
            "@types/react-dom": "^18",
            tailwindcss: "^3.4.0",
            postcss: "^8",
            autoprefixer: "^10",
          },
        },
        null,
        2,
      ),
    },
    { name: "next.config.mjs", content: "/** @type {import('next').NextConfig} */\nexport default {};\n" },
    {
      name: "tsconfig.json",
      content: JSON.stringify(
        {
          compilerOptions: {
            target: "ES2020", lib: ["dom", "dom.iterable", "esnext"], allowJs: true, skipLibCheck: true,
            strict: true, noEmit: true, esModuleInterop: true, module: "esnext", moduleResolution: "bundler",
            resolveJsonModule: true, isolatedModules: true, jsx: "preserve", incremental: true,
            plugins: [{ name: "next" }], paths: { "@/*": ["./*"] },
          },
          include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
          exclude: ["node_modules"],
        },
        null,
        2,
      ),
    },
    { name: "postcss.config.mjs", content: "export default { plugins: { tailwindcss: {}, autoprefixer: {} } };\n" },
    {
      name: "tailwind.config.ts",
      content:
        'import type { Config } from "tailwindcss";\nexport default {\n  content: ["./app/**/*.{ts,tsx}"],\n  theme: { extend: {} },\n  plugins: [],\n} satisfies Config;\n',
    },
    { name: "app/globals.css", content: "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n" },
    {
      name: "app/layout.tsx",
      content:
        'import "./globals.css";\n\nexport const metadata = { title: "' +
        slug +
        '" };\n\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang="en">\n      <body>{children}</body>\n    </html>\n  );\n}\n',
    },
    // The deliverable already begins with "use client" + react imports, so it
    // drops straight into app/page.tsx of a real Next app.
    { name: "app/page.tsx", content: pageSource.trim() + "\n" },
    {
      name: "README.md",
      content:
        `# ${slug}\n\nGenerated by Cofounder. A standalone Next.js + Tailwind landing page.\n\n` +
        "```bash\nnpm install\nnpm run dev   # http://localhost:3000\n```\n\n" +
        "Edit `app/page.tsx`. Deploy anywhere that runs Next.js (Vercel, Netlify, a Node host).\n",
    },
  ];
}

// GET /api/export/<artifactId>  -> downloadable .zip of a runnable Next.js project
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }): Promise<Response> {
  const { id } = await params;
  const artifact = await getArtifact(id).catch(() => null);
  if (!artifact || artifact.kind !== "landing_page") {
    return new Response("Not found, or this deliverable isn't an exportable site.", { status: 404 });
  }
  const slug = slugify(artifact.title);
  const zip = makeZip(nextProject(slug, artifact.content));
  return new Response(new Uint8Array(zip), {
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${slug}-nextjs.zip"`,
      "Cache-Control": "no-store",
    },
  });
}
