import type Anthropic from "@anthropic-ai/sdk";
import type { ArtifactKind } from "@/lib/agent-types";
import { deliverableFor } from "@/lib/agent-types";
import {
  dbConfigured,
  insertArtifact,
  patchTask,
} from "@/lib/supabase-rest";
import { getAnthropic, MODEL } from "@/lib/anthropic";

export const runtime = "nodejs";

interface ExecBody {
  workspaceId?: string;
  idea?: string;
  task?: { id: string; title: string; department: string; detail?: string };
}

function genPrompt(
  kind: ArtifactKind,
  noun: string,
  task: { title: string; department: string; detail?: string },
  idea: string,
): string {
  const ctx = `Company idea: "${idea || "a new startup"}".
Task: "${task.title}" (department: ${task.department}). ${task.detail ?? ""}`.trim();

  if (kind === "landing_page") {
    return `${ctx}

You are the Engineering agent. ACTUALLY BUILD the ${noun} — output a COMPLETE, single self-contained HTML5 document (inline <style>, no external assets, no scripts required) for this company's marketing landing page. Include a hero with a headline + subhead + CTA button, a 3-feature section, and a footer. Make it modern, clean, responsive, and on-brand for the idea. Output ONLY the raw HTML starting with <!DOCTYPE html> — no markdown fences, no commentary.`;
  }
  if (kind === "brand_spec") {
    return `${ctx}

You are the Design agent. Produce a real brand spec in Markdown: a one-line brand essence, a 5-color palette (with hex codes and usage), typography recommendation (heading + body), tone of voice (3 adjectives + a do/don't), and a logo concept description. Output ONLY Markdown.`;
  }
  if (kind === "email") {
    return `${ctx}

You are the Sales agent. Write a real, ready-to-send cold outbound email (subject line + body, <140 words, warm and specific, one clear CTA). Output ONLY Markdown with the subject on the first line as **Subject:** ...`;
  }
  return `${ctx}

You are the ${task.department} agent. Produce the actual ${noun} as concise, useful Markdown a founder could act on immediately. Output ONLY Markdown.`;
}

/* Deterministic, genuinely-usable fallback content (no API key needed). */
function mockArtifact(
  kind: ArtifactKind,
  noun: string,
  task: { title: string; department: string },
  idea: string,
): { title: string; content: string } {
  const name = (idea || "Your Company").slice(0, 60);
  if (kind === "landing_page") {
    return {
      title: `${name} — landing page`,
      content: `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${name}</title>
<style>
*{margin:0;box-sizing:border-box;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Inter,sans-serif}
body{background:#0b0b10;color:#e8e8ef}
.wrap{max-width:1000px;margin:0 auto;padding:0 24px}
header{display:flex;justify-content:space-between;align-items:center;padding:24px 0}
.logo{font-weight:700;letter-spacing:-.02em}
.hero{text-align:center;padding:96px 0}
.hero h1{font-size:clamp(34px,6vw,64px);line-height:1.05;letter-spacing:-.03em;background:linear-gradient(180deg,#fff,#9aa);-webkit-background-clip:text;background-clip:text;color:transparent}
.hero p{margin:20px auto 0;max-width:54ch;color:#aab;font-size:18px;line-height:1.5}
.cta{display:inline-block;margin-top:32px;background:#fff;color:#0b0b10;font-weight:600;padding:14px 28px;border-radius:10px;text-decoration:none}
.features{display:grid;gap:20px;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));padding:40px 0 96px}
.card{background:#16161f;border:1px solid #23232e;border-radius:16px;padding:24px}
.card h3{font-size:18px;margin-bottom:8px}
.card p{color:#99a;font-size:14px;line-height:1.5}
footer{border-top:1px solid #1d1d27;padding:32px 0;color:#778;text-align:center;font-size:13px}
</style></head>
<body><div class="wrap">
<header><span class="logo">${name}</span><a class="cta" href="#" style="margin:0;padding:8px 16px">Get started</a></header>
<section class="hero">
<h1>${name}</h1>
<p>${idea || "The fastest way to launch and grow your business."} Built and shipped by autonomous agents — you stay in control.</p>
<a class="cta" href="#">Start free</a>
</section>
<section class="features">
<div class="card"><h3>Ship faster</h3><p>Go from idea to a working product in a day, not a quarter.</p></div>
<div class="card"><h3>Stay in control</h3><p>Nothing ships without your approval. Review every step.</p></div>
<div class="card"><h3>Scale on autopilot</h3><p>Agents handle the busywork across every department.</p></div>
</section>
<footer>© 2026 ${name}. Generated by the Cofounder Engineering agent.</footer>
</div></body></html>`,
    };
  }
  if (kind === "brand_spec") {
    return {
      title: `${name} — brand spec`,
      content: `# ${name} — Brand Spec

**Essence:** Confident, modern, builder-friendly.

## Palette
| Role | Hex |
|---|---|
| Background | \`#0B0B10\` |
| Surface | \`#16161F\` |
| Primary | \`#6C5CE7\` |
| Accent | \`#34A853\` |
| Text | \`#E8E8EF\` |

## Typography
- **Headings:** Hanken Grotesk / geometric grotesque, tight tracking.
- **Body:** Inter, 15–16px, 1.5 line-height.

## Tone of voice
Direct · Optimistic · Precise.
- **Do:** speak to outcomes ("ship in a day").
- **Don't:** hedge or use corporate filler.

## Logo concept
A pixel-grid wordmark — rectilinear letterforms that read as a friendly operating system for running a company.`,
    };
  }
  if (kind === "email") {
    return {
      title: `${name} — outbound email`,
      content: `**Subject:** Thought ${name} could help you ship faster

Hi {{first_name}},

I noticed {{company}} is moving fast — most teams your size lose weeks on setup, GTM, and the busywork between. ${name} runs those as autonomous agents so a founder can go from idea to a working company in a day, with approval gates on anything risky.

Worth a 15-min look? I can spin up a live demo on your exact use case.

— {{sender}}`,
    };
  }
  return {
    title: `${name} — ${noun}`,
    content: `# ${task.title}

_${task.department} agent deliverable for ${name}._

- ✅ Step 1 — scoped and ready
- ✅ Step 2 — drafted
- ⏳ Step 3 — pending your approval

This is a generated starting point you can act on immediately.`,
  };
}

export async function POST(req: Request): Promise<Response> {
  let body: ExecBody = {};
  try {
    body = (await req.json()) as ExecBody;
  } catch {
    body = {};
  }
  const task = body.task;
  if (!task?.id || !task?.title) {
    return Response.json({ ok: false, error: "missing task" }, { status: 400 });
  }
  const idea = body.idea ?? "";
  const { kind, noun } = deliverableFor(task.department);

  let title = "";
  let content = "";
  let mock = true;

  const client = getAnthropic();
  if (client) {
    try {
      const resp = await client.messages.create({
        model: MODEL,
        max_tokens: 3000,
        messages: [
          { role: "user", content: genPrompt(kind, noun, task, idea) },
        ],
      });
      content = resp.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("\n")
        .trim()
        .replace(/^```[a-z]*\n?/i, "")
        .replace(/```$/i, "")
        .trim();
      title = `${(idea || "Company").slice(0, 50)} — ${noun}`;
      mock = content.length === 0;
    } catch {
      mock = true;
    }
  }

  if (mock || !content) {
    const m = mockArtifact(kind, noun, task, idea);
    title = m.title;
    content = m.content;
    mock = true;
  }

  // Persist the artifact + mark the task done.
  let artifactId: string | null = null;
  if (dbConfigured && body.workspaceId) {
    try {
      const art = await insertArtifact(body.workspaceId, {
        taskId: task.id,
        kind,
        title,
        content,
      });
      artifactId = art?.id ?? null;
      await patchTask(task.id, { status: "done" });
    } catch {
      /* fall through — still return the artifact to the client */
    }
  }

  return Response.json({
    ok: true,
    mock,
    artifact: { id: artifactId, taskId: task.id, kind, title, content },
  });
}
