// Render a generated React/Next page component live, with no build step: an
// HTML harness that loads React + ReactDOM + Tailwind + Babel-standalone from a
// CDN, transpiles the component in the browser, and mounts it. Used by the
// in-app preview (sandboxed iframe) and the public /p/<id> page.
//
// The component is generated by our own prompt, but we still treat it as
// semi-trusted: it always runs in a sandbox="allow-scripts" (null-origin) iframe
// so it can never read this origin's localStorage / cookies.

/** Strip imports / "use client" / exports so the bare component runs under Babel. */
function cleanComponent(raw: string): string {
  return raw
    .replace(/^﻿/, "")
    .replace(/```[a-z]*\n?/gi, "") // stray markdown fences
    // Drop the "use client" directive in any form (quoted or not, ; or not).
    .replace(/^[ \t]*['"]?use client['"]?;?[ \t\r]*$/gim, "")
    .replace(/^[ \t]*import[^\n]*$/gim, "") // deps are provided as globals
    .replace(/^[ \t]*export\s*\{[^}]*\};?[ \t]*$/gim, "")
    .replace(/export\s+default\s+(async\s+)?function\s+Page/m, "$1function Page")
    .replace(/export\s+default\s+/m, "var __Default = ")
    .replace(/^[ \t]*export\s+(const|function|let|var|class|async)\b/gm, "$1")
    .trim();
}

function escAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;");
}

/** Strip a UTF-8 BOM + any stray markdown code fences the model wrapped the
 *  output in, then trim. */
function stripFences(raw: string): string {
  return raw.replace(/^﻿/, "").replace(/```[a-z]*\n?/gi, "").trim();
}

/** True when the deliverable is a complete HTML document rather than a React/JSX
 *  component — e.g. the templated landing-page fallback, which starts with
 *  `<!DOCTYPE html>` / `<html>`. Such a doc is already a renderable page; running
 *  it through Babel as JSX throws "Unexpected token (1:0)" on the doctype. */
function looksLikeHtmlDocument(raw: string): boolean {
  const t = stripFences(raw);
  return /^<!doctype\s+html/i.test(t) || /^<html[\s>]/i.test(t);
}

/**
 * The executable harness document (React + Tailwind + Babel from CDN). Loaded
 * inside a sandboxed iframe — never served as a top-level page directly.
 */
export function buildReactHarness(rawCode: string, title = "Preview"): string {
  // A complete HTML document deliverable (the templated landing-page fallback, or
  // any raw HTML the model emits) is already a renderable page — return it as-is.
  // Babel-parsing `<!DOCTYPE html>` as JSX would throw "Unexpected token (1:0)".
  if (looksLikeHtmlDocument(rawCode)) {
    return stripFences(rawCode);
  }
  const cleaned = cleanComponent(rawCode);
  // Inject as a JS string literal; neutralize "</" so it can't close the script.
  const codeLiteral = JSON.stringify(cleaned).replace(/<\//g, "<\\/");
  const titleEsc = title.replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[c] as string);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${titleEsc}</title>
<script src="https://cdn.tailwindcss.com"></script>
<link rel="preconnect" href="https://fonts.googleapis.com"/><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Sora:wght@400;600;700;800&family=Space+Grotesk:wght@400;500;700&family=Manrope:wght@400;600;700;800&family=Plus+Jakarta+Sans:wght@400;600;700;800&family=DM+Sans:wght@400;500;700&family=Outfit:wght@400;600;700;800&display=swap" rel="stylesheet"/>
<script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/ScrollTrigger.min.js"></script>
<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<script src="https://unpkg.com/@babel/standalone@7/babel.min.js"></script>
<style>html,body{margin:0;padding:0}#__err{display:none;position:fixed;inset:0;margin:0;padding:24px;font:12px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace;color:#b00020;background:#fff;white-space:pre-wrap;overflow:auto;z-index:99999}</style>
</head><body>
<div id="root"></div><pre id="__err"></pre>
<script>
(function(){
  function showErr(m){var e=document.getElementById('__err');e.style.display='block';e.textContent='Preview error:\\n'+m;}
  if(!window.Babel||!window.React||!window.ReactDOM){showErr('Failed to load the preview runtime (React/Babel CDN blocked?).');return;}
  try{
    var code=${codeLiteral};
    var out=window.Babel.transform(code,{presets:[['typescript',{isTSX:true,allExtensions:true,onlyRemoveTypeImports:true}],'react'],filename:'page.tsx'}).code;
    var R=window.React;
    if(window.gsap&&window.ScrollTrigger){try{window.gsap.registerPlugin(window.ScrollTrigger);}catch(_){}}
    var make=new Function('React','useState','useEffect','useRef','useMemo','useCallback','useLayoutEffect','useReducer','useId','gsap','ScrollTrigger',
      out+'\\nreturn (typeof Page!=="undefined")?Page:(typeof __Default!=="undefined"?__Default:null);');
    var Page=make(R,R.useState,R.useEffect,R.useRef,R.useMemo,R.useCallback,R.useLayoutEffect,R.useReducer,R.useId,window.gsap,window.ScrollTrigger);
    if(!Page){showErr('No default-exported \`Page\` component was found in the deliverable.');return;}
    window.ReactDOM.createRoot(document.getElementById('root')).render(R.createElement(Page));
  }catch(e){showErr((e&&e.stack)||(e&&e.message)||String(e));}
})();
</script>
</body></html>`;
}

/**
 * A standalone page (for the public /p/<id> route) that hosts the harness in a
 * sandboxed, null-origin iframe — so the generated JS is isolated from this
 * origin even when served top-level.
 */
export function buildIsolatedReactPage(rawCode: string, title = "Preview"): string {
  const harness = escAttr(buildReactHarness(rawCode, title));
  const titleEsc = title.replace(/[<>&]/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;" })[c] as string);
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/><title>${titleEsc}</title>
<style>html,body{margin:0;height:100%}iframe{border:0;width:100vw;height:100vh;display:block}</style></head>
<body><iframe sandbox="allow-scripts" referrerpolicy="no-referrer" srcdoc="${harness}"></iframe></body></html>`;
}
